"use client";

import { useChat } from "ai/react";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { 
  Scale, 
  Shield, 
  Mic, 
  Send, 
  Bot, 
  User, 
  ChevronDown,
  Loader2,
  ArrowLeft,
  Sparkles,
  Square,
  Download
} from "lucide-react";

export default function BharatJurisChat() {
  // 1. LANGUAGE CONFIGURATION
  const languages = [
    { code: 'en-IN', short: 'EN', label: 'English', prompt: 'Answer in professional English.' },
    { code: 'hi-IN', short: 'HI', label: 'Hindi', prompt: 'Answer in Hindi (Devanagari).' },
    { code: 'mr-IN', short: 'MR', label: 'Marathi', prompt: 'Answer in Marathi.' },
    { code: 'gu-IN', short: 'GU', label: 'Gujarati', prompt: 'Answer in Gujarati.' },
    { code: 'ta-IN', short: 'TA', label: 'Tamil', prompt: 'Answer in Tamil.' },
    { code: 'te-IN', short: 'TE', label: 'Telugu', prompt: 'Answer in Telugu.' },
  ];
  
  // Default to English
  const [selectedLang, setSelectedLang] = useState(languages[0]);
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  // 2. CORE AI HOOK
  const { messages, input, setInput, handleInputChange, handleSubmit, isLoading } = useChat({
    api: "/api/chat",
    body: { languagePrompt: selectedLang.prompt },
    initialMessages: [
      {
        id: "welcome",
        role: "assistant",
        content: "Namaste. I am Nyaya Sahayak, your AI Legal Assistant. \n\nI can help you understand the Bharatiya Nyaya Sanhita (BNS), simplify legal notices, or provide guidance on Indian Law. \n\n**Note:** My responses are for informational purposes and do not constitute official legal advice."
      }
    ]
  });

  // 3. STATE FOR VOICE
  const [isListening, setIsListening] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const recognitionRef = useRef<any>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isLoading]);

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsDropdownOpen(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  // --- DOWNLOAD CHAT FUNCTION ---
  const handleDownloadChat = () => {
    if (messages.length <= 1) {
        alert("No conversation to download yet.");
        return;
    }

    let chatHtml = messages.map(m => {
        const role = m.role === 'user' ? 'You' : 'Nyaya Sahayak';
        const color = m.role === 'user' ? '#000000' : '#003366'; 
        const bg = m.role === 'user' ? '#f0f0f0' : '#ffffff';
        
        const cleanContent = m.content
          .replace(/\*\*(.*?)\*\*/g, '<b>$1</b>')
          .replace(/\n/g, '<br/>');
        
        return `
            <div style="margin-bottom: 15px; padding: 10px; background-color: ${bg}; border-radius: 5px; border: 1px solid #ddd;">
                <p style="margin: 0 0 5px 0; color: ${color}; font-size: 10pt; font-weight: bold; text-transform: uppercase;">${role}</p>
                <div style="font-size: 11pt; color: #333; line-height: 1.5;">${cleanContent}</div>
            </div>
        `;
    }).join('');

    const header = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head><meta charset='utf-8'><title>Legal Consultation History</title>
      <style>
        body { font-family: 'Times New Roman', serif; font-size: 12pt; line-height: 1.5; color: #000; margin: 20px; }
        h1 { text-align: center; text-decoration: underline; color: #000; font-size: 16pt; margin-bottom: 30px; text-transform: uppercase; }
        p.meta { text-align: center; color: #666; font-size: 10pt; margin-bottom: 40px; }
      </style>
      </head><body>
      <h1>LEGAL CONSULTATION TRANSCRIPT</h1>
      <p class="meta">Generated by BharatJuris on ${new Date().toLocaleDateString()}</p>
      <hr style="border: 0; border-top: 2px solid #000; margin-bottom: 30px;" />
      ${chatHtml}
      <br/><br/>
      <hr/>
      <p style="text-align: center; font-size: 9pt; color: #888;">Disclaimer: This transcript is generated by AI for informational purposes only and does not constitute official legal advice.</p>
      </body></html>
    `;

    const source = 'data:application/vnd.ms-word;charset=utf-8,' + encodeURIComponent(header);
    const fileDownload = document.createElement("a");
    document.body.appendChild(fileDownload);
    fileDownload.href = source;
    fileDownload.download = `Consultation_History_${new Date().toISOString().split('T')[0]}.doc`;
    fileDownload.click();
    document.body.removeChild(fileDownload);
  };

  const handleVoiceInput = () => {
    if (!('webkitSpeechRecognition' in window || 'SpeechRecognition' in window)) {
      alert("Voice input is not supported in this browser. Please use Chrome or Edge.");
      return;
    }

    if (isListening) {
      if (recognitionRef.current) {
        recognitionRef.current.stop();
        recognitionRef.current = null;
      }
      setIsListening(false);
      return;
    }

    const SpeechRecognition = (window as any).webkitSpeechRecognition || (window as any).SpeechRecognition;
    const recognition = new SpeechRecognition();
    recognition.lang = selectedLang.code;
    recognition.continuous = true; 
    recognition.interimResults = true;

    recognitionRef.current = recognition;
    setIsListening(true);

    recognition.onresult = (event: any) => {
      let finalTranscript = '';
      for (let i = event.resultIndex; i < event.results.length; ++i) {
        if (event.results[i].isFinal) {
          finalTranscript += event.results[i][0].transcript;
        }
      }
      if (finalTranscript) {
        setInput((prev) => prev + (prev && !prev.endsWith(' ') ? " " : "") + finalTranscript);
      }
    };

    recognition.onerror = (event: any) => { console.error(event.error); setIsListening(false); };
    recognition.onend = () => { setIsListening(false); };
    recognition.start();
  };

  return (
    <div className="flex h-screen bg-[#050505] text-white font-sans overflow-hidden">
      
      {/* --- SIDEBAR --- */}
      <aside className="w-72 border-r border-[#1f1f1f] flex flex-col bg-[#0a0a0a] hidden md:flex z-20">
        <div className="p-6 flex items-center gap-3">
          <Scale className="w-7 h-7 text-white" />
          <span className="font-bold text-xl tracking-wide">BharatJuris</span>
        </div>
        
        <div className="flex-1 flex flex-col justify-center items-center p-8 opacity-80">
            <Shield className="w-12 h-12 text-gray-600 mb-4 opacity-50" />
            <p className="text-sm text-gray-500 font-medium text-center">Conversations are private and secure.</p>
        </div>
      </aside>

      {/* --- MAIN AREA --- */}
      <main className="flex-1 flex flex-col relative bg-[#050505] overflow-hidden">
        
        {/* --- GLOW EFFECT --- */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-blue-900/10 rounded-full blur-[100px] pointer-events-none" />

        {/* Header */}
        <header className="h-16 border-b border-[#1f1f1f] flex items-center px-6 justify-between bg-[#0a0a0a]/50 backdrop-blur-md sticky top-0 z-10">
          <div className="flex items-center gap-4">
             <Link href="/" className="p-2 text-gray-400 hover:text-white hover:bg-[#1a1a1a] rounded-full transition-colors">
                <ArrowLeft className="w-5 h-5" />
             </Link>

             <div>
                <h1 className="font-bold text-white text-lg leading-tight">Nyaya Sahayak</h1>
                <div className="flex items-center gap-2">
                    <span className="relative flex h-2 w-2">
                      <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
                      <span className="relative inline-flex rounded-full h-2 w-2 bg-green-500"></span>
                    </span>
                    <span className="text-[10px] text-gray-400 uppercase tracking-wider font-semibold">Online • AI Legal Assistant</span>
                </div>
             </div>
          </div>

          <div className="flex items-center gap-3">
              {/* DOWNLOAD BUTTON */}
              <button 
                onClick={handleDownloadChat}
                className="hidden md:flex items-center gap-2 px-3 py-1.5 rounded-lg border border-[#333] bg-[#111] hover:bg-[#222] hover:border-blue-500/50 transition-all text-sm text-gray-300"
                title="Download Chat History"
              >
                <Download className="w-4 h-4" />
                <span className="hidden lg:inline">Download Chat</span>
              </button>

              {/* LANGUAGE DROPDOWN */}
              <div className="relative" ref={dropdownRef}>
                <button 
                    onClick={() => setIsDropdownOpen(!isDropdownOpen)}
                    className="flex items-center gap-2 px-3 py-1.5 rounded-lg border border-[#333] bg-[#111] hover:border-gray-600 transition-all text-sm group"
                >
                    <span className="flex items-center justify-center w-5 h-5 bg-blue-600 text-[10px] font-bold rounded text-white">
                        {selectedLang.short}
                    </span>
                    <span className="text-gray-200">{selectedLang.label}</span>
                    <ChevronDown className={`w-4 h-4 text-gray-500 transition-transform ${isDropdownOpen ? 'rotate-180' : ''}`} />
                </button>
                
                {isDropdownOpen && (
                    <div className="absolute right-0 top-full mt-2 w-48 bg-[#111] border border-[#333] rounded-xl shadow-xl overflow-hidden z-50 animate-in fade-in slide-in-from-top-2">
                        {languages.map((lang) => (
                        <button
                            key={lang.code}
                            onClick={() => {
                                setSelectedLang(lang);
                                setIsDropdownOpen(false);
                            }}
                            className={`w-full text-left px-4 py-3 text-sm hover:bg-[#222] transition-colors flex items-center gap-3 ${
                            selectedLang.code === lang.code ? 'bg-[#1a1a1a]' : ''
                            }`}
                        >
                            <span className={`flex items-center justify-center w-6 h-6 text-[10px] font-bold rounded-full ${
                                selectedLang.code === lang.code 
                                ? 'bg-blue-600 text-white' 
                                : 'bg-[#333] text-gray-400'
                            }`}>
                                {lang.short}
                            </span>
                            <span className={selectedLang.code === lang.code ? 'text-white font-medium' : 'text-gray-300'}>
                                {lang.label}
                            </span>
                        </button>
                        ))}
                    </div>
                )}
              </div>
          </div>
        </header>

        {/* Messages */}
        <div className="flex-1 overflow-y-auto p-4 md:p-8 space-y-6 scrollbar-thin scrollbar-thumb-gray-800 z-10">
            {messages.map((m) => (
                <div key={m.id} className={`flex gap-4 ${m.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                    
                    {/* Bot Avatar */}
                    {m.role !== 'user' && (
                        <div className="w-8 h-8 rounded-lg border border-[#333] flex items-center justify-center bg-[#111] flex-shrink-0 mt-1">
                            <Bot className="w-4 h-4 text-blue-400" />
                        </div>
                    )}
                    
                    {/* Message Bubble */}
                    <div className={`max-w-[85%] p-4 rounded-2xl text-[15px] shadow-sm ${
                        m.role === 'user' 
                        ? 'bg-[#2563eb] text-white rounded-br-none' 
                        : 'bg-[#1a1a1a] text-gray-200 border border-[#333] rounded-bl-none' 
                    }`}>
                        {m.role === 'user' ? (
                            <p className="whitespace-pre-wrap leading-relaxed">{m.content}</p>
                        ) : (
                            <ReactMarkdown 
                              remarkPlugins={[remarkGfm]}
                              components={{
                                strong: ({node, ...props}) => <span className="font-bold text-blue-400" {...props} />,
                                p: ({node, ...props}) => <p className="mb-2 last:mb-0 leading-relaxed" {...props} />,
                                ul: ({node, ...props}) => <ul className="list-disc list-inside ml-2 mb-2 space-y-1 text-gray-300" {...props} />,
                                ol: ({node, ...props}) => <ol className="list-decimal list-inside ml-2 mb-2 space-y-1 text-gray-300" {...props} />,
                                li: ({node, ...props}) => <li className="marker:text-blue-500 pl-1" {...props} />,
                                h1: ({node, ...props}) => <h1 className="text-xl font-bold mt-4 mb-2 text-white" {...props} />,
                                h2: ({node, ...props}) => <h2 className="text-lg font-bold mt-3 mb-2 text-white" {...props} />,
                                h3: ({node, ...props}) => <h3 className="text-md font-semibold mt-2 mb-1 text-white" {...props} />,
                                blockquote: ({node, ...props}) => <blockquote className="border-l-2 border-blue-500 pl-4 italic text-gray-400 my-2" {...props} />,
                                code: ({node, ...props}) => <code className="bg-black/30 px-1 py-0.5 rounded text-blue-300 font-mono text-sm" {...props} />,
                              }}
                            >
                              {m.content}
                            </ReactMarkdown>
                        )}
                    </div>

                    {/* User Avatar */}
                    {m.role === 'user' && (
                        <div className="w-8 h-8 rounded-full bg-gradient-to-br from-gray-700 to-gray-600 flex items-center justify-center flex-shrink-0 mt-1">
                            <User className="w-4 h-4 text-white" />
                        </div>
                    )}
                </div>
            ))}
            
            {/* Loading State */}
            {isLoading && (
                 <div className="flex gap-4">
                    <div className="w-8 h-8 rounded-lg border border-[#333] flex items-center justify-center bg-[#111]">
                        <Bot className="w-4 h-4 text-blue-400" />
                    </div>
                    <div className="bg-[#1a1a1a] px-5 py-4 rounded-2xl border border-[#333] rounded-bl-none">
                        <div className="flex gap-1.5 items-center text-xs text-gray-500">
                            <Sparkles className="w-3 h-3 animate-spin" />
                            Thinking...
                        </div>
                    </div>
                 </div>
            )}
            <div ref={messagesEndRef} />
        </div>

        {/* Input Area */}
        <div className="p-6 bg-[#050505] z-20">
            <div className="max-w-4xl mx-auto relative group">
                <form onSubmit={handleSubmit} className="relative flex items-center bg-[#111] border border-[#333] rounded-2xl focus-within:border-gray-600 focus-within:ring-1 focus-within:ring-gray-600 transition-all shadow-lg">
                    <input 
                        value={input}
                        onChange={handleInputChange}
                        placeholder={isListening ? "Listening... (Click Red icon to stop)" : `Ask in ${selectedLang.label}...`}
                        className="w-full bg-transparent text-white py-4 pl-6 pr-32 focus:outline-none placeholder-gray-600"
                        disabled={isLoading}
                    />
                    
                    <div className="absolute right-3 flex items-center gap-2">
                        {/* Voice Button */}
                        <button 
                          type="button" 
                          onClick={handleVoiceInput}
                          className={`p-2 rounded-full transition-all ${
                            isListening 
                            ? 'bg-red-500/20 text-red-500 animate-pulse hover:bg-red-500/30' 
                            : 'text-gray-400 hover:text-white hover:bg-gray-800'
                          }`}
                          title={isListening ? "Stop Recording" : "Start Voice Input"}
                        >
                            {isListening ? <Square className="w-5 h-5 fill-current" /> : <Mic className="w-5 h-5" />}
                        </button>
                        
                        {/* Send Button */}
                        <button 
                            type="submit" 
                            disabled={isLoading || !input}
                            className="bg-blue-600 text-white p-2.5 rounded-xl hover:bg-blue-500 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-md"
                        >
                            <Send className="w-4 h-4" />
                        </button>
                    </div>
                </form>
                
                <div className="text-center mt-3 flex justify-center items-center gap-2 opacity-60">
                    <p className="text-[10px] text-gray-500 uppercase tracking-widest font-medium">
                        AI Generated • Verify with Article 39A
                    </p>
                </div>
            </div>
        </div>

      </main>
    </div>
  );
}